In [2]:
import numpy as np

a = np.array([[3,3,4],
            [4,2,9],
            [9,3,7]])
a

array([[3, 3, 4],
       [4, 2, 9],
       [9, 3, 7]])

In [9]:
b = a.T
b

array([[3, 4, 9],
       [3, 2, 3],
       [4, 9, 7]])

In [5]:
c = np.copy(a)
c

array([[3, 3, 4],
       [4, 2, 9],
       [9, 3, 7]])

In [6]:
c[0, 2] = 10
c

array([[ 3,  3, 10],
       [ 4,  2,  9],
       [ 9,  3,  7]])

In [7]:
c[1, 1] = 25
c

array([[ 3,  3, 10],
       [ 4, 25,  9],
       [ 9,  3,  7]])

In [ ]:
e = b.dot(c)
e

array([[106, 136, 129],
       [ 44,  68,  69],
       [111, 258, 170]])

In [11]:
b @ c

array([[106, 136, 129],
       [ 44,  68,  69],
       [111, 258, 170]])

In [13]:
f = np.where(e < 100, e, 10*e)
f

array([[1060, 1360, 1290],
       [  44,   68,   69],
       [1110, 2580, 1700]])