In [1]:
import numpy as np

In [2]:
a = np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a[2:6]

array([2, 3, 4, 5])

In [5]:
a[1:5] = 50
a

array([ 0, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
b = a[0:4]
b

array([ 0, 50, 50, 50])

In [7]:
b[:]=91
b

array([91, 91, 91, 91])

In [8]:
a

array([91, 91, 91, 91, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
c = a.copy()
c

array([91, 91, 91, 91, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a_m = np.array([[3,2,5], [4,3,0], [9,2,9]])
a_m

array([[3, 2, 5],
       [4, 3, 0],
       [9, 2, 9]])

In [14]:
a_m[0:2, 1:]

array([[2, 5],
       [3, 0]])

In [ ]:
b = np.zeros((10, 10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
b[3:8, 7:9]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])